#! /bin/bash
set -eu

APT="sudo apt-get -q -y"
CABAL_INSTALL_DEPS="cabal install --only-dependencies --force-reinstall"

$APT update
$APT install dctrl-tools
$APT install ghc6

$CABAL_INSTALL_DEPS "$@" # Install the rest via Hackage

cabal install hlint

